# Generated by Django 5.1.7 on 2025-04-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('consulting', models.CharField(max_length=100)),
            ],
        ),
    ]
