# Generated by Django 5.1.7 on 2025-04-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='addr',
            new_name='add',
        ),
    ]
