# Generated by Django 5.1.7 on 2025-04-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_rename_addr_patient_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='add',
            new_name='address',
        ),
    ]
